/*
# Seed center-hifz department + all missing content data

1. Purpose
- center-hifz is the only department without a seed migration (halqa, charity,
  school already have one). This inserts it.
- Also seeds announcements, posts, testimonials, timeline_events, and
  site_settings — all of which are empty on a fresh DB.

2. All inserts use ON CONFLICT DO NOTHING so re-running is safe.
*/

-- ============ center-hifz department ============
INSERT INTO departments (id, slug, name, short_description, full_description, mission, vision, values, objectives, established_date, logo_key, cover_image_key, cover_image, accent_color, stats, programs, telegram_link, telegram_chat_id, registration_status, registration_fields, requirements)
VALUES (
  'dept-hifz',
  'center-hifz',
  '{"ar":"مركز لحفظ القرآن الكريم دار القرآن","en":"Dar Al-Quran Quran Memorization Center","am":"የቁርአን ማስታወሻ ማዕከል","om":"Wiirtuu Hafzu Quraanaa Daar Al-Quraan"}'::jsonb,
  '{"ar":"مركز سكني لتخريج الحافظات لكتاب الله كاملاً، على يد نخبة من المعلمات المؤهلات","en":"A residential center for graduating female Hafizat of the complete Quran, taught by qualified female Ustazas","am":"የቁርአን ሙሉ ማስታወሻ ለሚያደርጉ ሴት ተማሪዎች የሚዘጋጀ ማዕከል፣ በብቁ የሴት መምህራን የሚማርበት","om":"Wiirtuu qophiiftuu hafzuu Quraana guutuu dubartoota barsiisuu, kan ogeeyyii Ustazaa dhiiraa"}'::jsonb,
  '{"ar":"مركز سكني متخصص في حفظ القرآن الكريم كاملاً للنساء، تأسس عام 1446هـ. يقدم المركز برنامجاً مكثفاً مدته سنتان، تُدرّس فيه المعلمات المؤهلات فقط. يوفر المركز جميع احتياجات الطالبات من السكن والطعام والمواد التعليمية ومستلزمات النظافة والرعاية الطبية، في بيئة آمنة ومحفزة على حفظ كتاب الله.","en":"A residential center specializing in the complete memorization of the Quran for women, established in 1446H. The center offers an intensive two-year program taught exclusively by qualified female Ustazas. It provides all student needs including accommodation, food, learning materials, hygiene supplies, and medical care in a safe environment conducive to memorizing the Book of Allah.","am":"ለሴቶች የቁርአን ሙሉ ማስታወሻ ለማድረግ የተዘጋጀ የመኖሪያ ማዕከል፣ በ1446ሂ የተመሰረተ። ማዕከሉ የሁለት ዓመት ጠንካራ ፕሮግራም ያቀርባል። ሁሉንም የተማሪዎችን ፍላጎቶች ያቀርባል።","om":"Wiirtuu qophiiftuu hafzuu Quraana guutuu dubartootaaf, 1446H kan hundeeffame. Piroogiraamii waggaa lamaa kan dandeessaa, kan Ustazaa dubartoota qofatu barsiisan. Haajiisa barattootaa hunda kenna."}'::jsonb,
  '{"ar":"تخريج حافظات متقنات لكتاب الله تعالى، متمكنات في العلوم الشرعية، مؤهلات لتعليم القرآن في مجتمعاتهن","en":"To graduate female Hafizat with precise mastery of the Book of Allah, competent in Islamic sciences, and qualified to teach the Quran in their communities","am":"የቁርአንን በትክክል የሚያስታውሱ እና ለማስተማር የሚበቁ ሴት ምሩቃን ማምረት","om":"Hafzuu Quraana sirrii qabuu fi hawaasa keessatti barsiisuu kan danda''u dubartoota baasuu"}'::jsonb,
  '{"ar":"أن يكون المركز منارة لحفظ كتاب الله تعالى للنساء في المنطقة، يُخرّج حافظات يجمعن بين الإتقان والفهم","en":"To be a beacon for women''s Quran memorization in the region, graduating Hafizat who combine mastery with understanding","am":"በክልሉ ለሴቶች የቁርአን ማስታወሻ መብራት መሆን፣ የሚያቀርብ ምሩቃን ማምረት","om":"Naannoo kanaatti dubartootaaf wiirtuu hafzu Quraanaa ta''uu, kan hubannoo fi sirrii qaban baasuu"}'::jsonb,
  '[{"ar":"الإتقان في الحفظ","en":"Mastery in memorization","am":"በማስታወሻ ትክክለኝነት","om":"Hafzuu keessatti sirrii"},{"ar":"الإخلاص لله تعالى","en":"Sincerity to Allah","am":"ለአላህ ቅንነት","om":"Rabbitti qajeelummaa"},{"ar":"الرعاية المتكاملة","en":"Comprehensive care","am":"የተሟላ እንክብካቤ","om":"Tajaasila guutuu"},{"ar":"الأخوّة في الله","en":"Sisterhood in Allah","am":"በአላህ የእህትነት ግንኙነት","om":"Haadha manaa Rabbii"}]'::jsonb,
  '[{"ar":"حفظ القرآن الكريم كاملاً مع الإتقان","en":"Memorize the complete Quran with mastery","am":"ቁርአንን በሙሉ በትክክል ማስታወስ","om":"Quraana guutuu sirrii hafzuu"},{"ar":"دراسة العلوم الشرعية المرافقة","en":"Study accompanying Islamic sciences","am":"የተያያዙ የእስላም ሳይንሶችን መማር","om":"Saayinsii Islaamaa walitti qabame qorachuu"},{"ar":"تأهيل المعلمات لنشر العلم","en":"Qualify teachers to spread knowledge","am":"ምሁራንን ለማሰልጠን","om":"Barsiisota beekumsa faca''uuf qopheessuu"}]'::jsonb,
  '1446 هـ',
  'center-hifz',
  'center-hifz',
  'https://images.pexels.com/photos/32108431/pexels-photo-32108431.jpeg?auto=compress&cs=tinysrgb&w=1600',
  '{"base":"#1E3A8A","accent":"#F59E0B"}'::jsonb,
  '[{"label":{"ar":"المقبولات في الدفعة الأولى","en":"Accepted in first batch","am":"በመጀመሪያው ወረቀት የተቀበሉ","om":"Dhabbata tokkoffaa qabiyyee"},"value":20},{"label":{"ar":"الخريجات بحفظ كامل","en":"Graduated with full memorization","am":"በሙሉ ማስታወሻ የተመረቁ","om":"Hafzuu guutuu milkaa''anii"},"value":18},{"label":{"ar":"الهدف للدفعة القادمة","en":"Target for next intake","am":"ለቀጣዩ ዒላማ","om":"Dhabbata itti aanfuu"},"value":30}]'::jsonb,
  '[]'::jsonb,
  'https://t.me/daralquran_hifz',
  '-1001234567890',
  'open',
  '[{"name":"fullName","label":{"ar":"الاسم الكامل","en":"Full Name","am":"ሙሉ ስም","om":"Maqaa guddaa"},"type":"text","required":true},{"name":"phone","label":{"ar":"رقم الهاتف","en":"Phone Number","am":"ስልክ ቁጥር","om":"Lakkoofsa bilbila"},"type":"tel","required":true},{"name":"age","label":{"ar":"العمر","en":"Age","am":"ዕድሜ","om":"Umuri"},"type":"number","required":true},{"name":"educationLevel","label":{"ar":"المستوى التعليمي","en":"Education Level","am":"የትምህርት ደረጃ","om":"Sadarkaa barumsaa"},"type":"select","required":true,"options":[{"ar":"ابتدائي","en":"Elementary","am":"አንደኛ ደረጃ","om":"Sadarkaa tokkoffaa"},{"ar":"إعدادي","en":"Middle School","am":"ሁለተኛ ደረጃ","om":"Sadarkaa lammaffaa"},{"ar":"ثانوي","en":"High School","am":"ሦስተኛ ደረጃ","om":"Sadarkaa sadaffaa"},{"ar":"جامعي","en":"University","am":"ዩኒቨርሲቲ","om":"Yunivarsiitii"}]},{"name":"hifzLevel","label":{"ar":"مستوى الحفظ الحالي","en":"Current Memorization Level","am":"የአሁን ማስታወሻ ደረጃ","om":"Sadarkaa hafzuu ammaa"},"type":"select","required":true,"options":[{"ar":"لا شيء","en":"None","am":"የለም","om":"Homaa"},{"ar":"جزء عمّ","en":"Juz Amma","am":"ጁዝ አማ","om":"Juz Amma"},{"ar":"أكثر من جزء","en":"More than one Juz","am":"ከአንድ ጁዝ በላይ","om":"Dibaayye juzii"},{"ar":"حفظ كامل","en":"Complete Hifz","am":"ሙሉ ማስታወሻ","om":"Hafzuu guutuu"}]},{"name":"address","label":{"ar":"العنوان","en":"Address","am":"አድራሻ","om":"Teessoo"},"type":"text","required":false},{"name":"notes","label":{"ar":"ملاحظات","en":"Notes","am":"ማስታወሻዎች","om":"Gabaaboo"},"type":"textarea","required":false}]'::jsonb,
  '{"ar":"الشروط: أن تكون الطالبة مسلمة، متحمسة لحفظ القرآن كاملاً، قادرة على الالتزام بالبرنامج السكني المكثف لمدة سنتين، ولديها دعم من ولي أمرها. النجاح في المقابلة الشخصية وتقييم مستوى الحفظ.","en":"Requirements: The student must be Muslim, motivated to memorize the entire Quran, able to commit to the intensive two-year residential program, and have guardian support. Passing the personal interview and memorization level assessment.","am":"ሁኔታዎች፡ ተማሪዋ ሙስሊም መሆን፣ ቁርአንን ሙሉ ለማስታወስ ተነሳሽነት እንዳላት፣ ለሁለት ዓመት የመኖሪያ ፕሮግራም ለመከታተል መቻሉ፣ ከወላጆቿ ድጋፍ እንዳላት። የግል ቃለ-መጠይቅ ማለፍ።","om":"Eegumsa: Barartuun Muslimaatti, Quraana guutuu hafzuuf carraaqqi, waggaa lamaa piroogiraamii qophiif ta''e hordofuu danda''u, deggersa abbaa itti aanfamtootaa qabuu. Gaaffii dhuunfaa darbuu."}'::jsonb
)
ON CONFLICT (slug) DO NOTHING;

-- ============ announcements ============
INSERT INTO announcements (id, title, department_slug, date, image, excerpt, content) VALUES
('ann-org-1', '{"ar":"افتتاح التسجيل في مركز حفظ القرآن الكريم","en":"Registration Opens at the Quran Memorization Center","am":"በቁርአን ማስታወሻ ማዕከል ምዝገባ ተከፍቷል","om":"Wiirtuu Hafzu Quraanaatti galmaa''uun banameera"}'::jsonb, 'org', '2025-04-10', 'https://images.pexels.com/photos/8145478/pexels-photo-8145478.jpeg?auto=compress&cs=tinysrgb&w=800', '{"ar":"يُعلن مركز حفظ القرآن الكريم عن فتح باب التسجيل للدفعة الثانية، الهدف 30 طالبة","en":"The Quran Memorization Center announces registration for the second batch, target 30 students","am":"የቁርአን ማስታወሻ ማዕከል ለሁለተኑ ወረቀት ምዝገባ ክፍቷል","om":"Wiirtuun Hafzu Quraanaa galmaa''insa dhabbata lammaffaa banuuteera"}'::jsonb, '{"ar":"بسم الله الرحمن الرحيم. يُعلن مركز حفظ القرآن الكريم دار القرآن عن فتح باب التسجيل للدفعة الثانية من الطالبات الراغبات في حفظ كتاب الله كاملاً. يستقبل المركز 30 طالبة في هذه الدفعة، على أن يلتزمن بالبرنامج السكني المكثف لمدة سنتين. تُوفر إدارة المركز جميع احتياجات الطالبات من السكن والطعام والمواد التعليمية والرعاية الطبية. يُرجى التواصل عبر قناة التيليجرام الخاصة بالمركز للحصول على تفاصيل التسجيل.","en":"In the name of Allah, the Most Gracious, the Most Merciful. The Dar Al-Quran Memorization Center announces the opening of registration for the second batch of female students wishing to memorize the complete Quran. The center accepts 30 students in this batch, committing to the intensive residential program for two years. The center administration provides all student needs. Please contact via the center''s Telegram channel for registration details.","am":"በአላህ ስም እንደምን እንዳናገኝ። የቁርአን ማስታወሻ ማዕከል ለሁለተኑ ወረቀት ምዝገባ ክፍቷል። 30 ተማሪዎችን ይቀበላል።","om":"Magaa Rabbiiin. Wiirtuun Hafzu Quraanaa galmaa''insa dhabbata lammaffaa banuuteera. Barattoota 30 qabachuu ni danda''a."}'::jsonb),
('ann-org-2', '{"ar":"كلمة رئيس المؤسسة بمناسبة العام الجديد","en":"Message from the Institution President on the New Year","am":"የተቋሙ ፕሬዝዳንት በአዲሱ ዓመት መልዕክት","om":"Ergaa mootummaa ogeessa waggaa haaraa irraa"}'::jsonb, 'org', '2025-03-15', 'https://images.pexels.com/photos/8145478/pexels-photo-8145478.jpeg?auto=compress&cs=tinysrgb&w=800', '{"ar":"يتقدم رئيس المؤسسة بخالص الشكر والتقدير للمعلمين والمتبرعين وأهالي الطلاب","en":"The institution president extends gratitude to teachers, donors, and student families","am":"የተቋሙ ፕሬዝዳንት ለመምህራን፣ ለተበራከቱ እና ለቤተሰቦች ምስጋና ይግባኝ ይላሉ","om":"Caqaa dhaabbata kanaa ogeeyyii, deggersitoota fi maatii barattootaa galateeffata jira"}'::jsonb, '{"ar":"بسم الله الرحمن الرحيم. يتقدم رئيس مؤسسة دار القرآن الكريم لخديجة بنت خويلد بخالص الشكر والتقدير لجميع المعلمين والمعلمات والمتبرعين وأهالي الطلاب على جهودهم المخلصة في خدمة كتاب الله تعالى. إن المؤسسة تسعى دائماً لتقديم الأفضل لأبنائنا وبناتنا في جميع الأقسام. نسأل الله التوفيق والسداد.","en":"In the name of Allah. The president of Dar Al-Quran Al-Kareem Institution extends sincere gratitude to all teachers, donors, and student families for their dedicated efforts in serving the Book of Allah. The institution continuously strives to provide the best for our children across all departments. We ask Allah for success and guidance.","am":"በአላህ ስም። የዳር አል-ቁርአን ተቋም ፕሬዝዳንት ለሁሉም መምህራን፣ ለተበራከቱ እና ለቤተሰቦች እውነተኛ ምስጋና ያቀርባሉ።","om":"Magaa Rabbii. Caqaan dhaabbata Daar Al-Quraan ogeeyyii hunda, deggersitoota fi maatii barattootaa galateeffata jira."}'::jsonb),
('ann-org-3', '{"ar":"حفل تخريج الدفعة الأولى من الحافظات","en":"First Batch Hafizat Graduation Ceremony","am":"የመጀመሪያው ወረቀት የሂፍዝ ምሩቃን ምረቃ ሥነ ሥርዓት","om":"Dhabbata tokkoffaa Hafzuu milkaa''ina shubbisa"}'::jsonb, 'org', '2024-12-20', 'https://images.pexels.com/photos/8145478/pexels-photo-8145478.jpeg?auto=compress&cs=tinysrgb&w=800', '{"ar":"احتفل المركز بتخريج 18 حافظة لكتاب الله كاملاً في حفل مهيب","en":"The center celebrated the graduation of 18 female Hafizat of the complete Quran in a grand ceremony","am":"ማዕከሉ 18 የቁርአን ምሩቃን በታላቅ ሥነ ሥርዓት አስተናገደ","om":"Wiirtuun Hafzu Quraanaa 18 milkaa''intota shubbisa guddaan kabajjateera"}'::jsonb, '{"ar":"في ليلة مباركة، احتفل مركز حفظ القرآن الكريم دار القرآن بتخريج الدفعة الأولى من الحافظات، حيث أتممن حفظ القرآن الكريم كاملاً بإتقان. بلغ عدد الخريجات 18 حافظة، تم تأهيلهن خلال سنتين من الدراسة المكثفة. شهد الحفل حضوراً كبيراً من أهالي الطالبات ومشايخ المنطقة وكلمات تأثيرية من الخريجات.","en":"On a blessed night, the Dar Al-Quran Memorization Center celebrated the graduation of the first batch of Hafizat, who completed the memorization of the entire Quran with mastery. 18 female students graduated after two years of intensive study. The ceremony was attended by students'' families, regional scholars, and featured impactful speeches from the graduates.","am":"በቡሩክ ምሽት፣ የቁርአን ማስታወሻ ማዕከል የመጀመሪያውን ወረቀት ምሩቃን አስተናገደ። 18 ተማሪዎች በሁለት ዓመት ጥናት ተመረቁ።","om":"Halkan barakaadha, Wiirtuun Hafzu Quraanaa dhabbata tokkoffaa milkaa''intota kabajjateera. 18 dubartoota waggaa lama qoratanii milkaa''anii ba''an."}'::jsonb),
('ann-3', '{"ar":"بدء العام الدراسي الجديد في المدرسة","en":"New School Year Begins","am":"አዲስ የትምህርት ዓመት ተጀምሯል","om":"Waggaa barumsaa haaraa eegaleera"}'::jsonb, 'school', '2025-02-01', 'https://images.pexels.com/photos/8145478/pexels-photo-8145478.jpeg?auto=compress&cs=tinysrgb&w=800', '{"ar":"استقبلت المدرسة أكثر من 642 طالباً وطالبة في بداية العام الدراسي الجديد","en":"The school welcomed over 642 students at the start of the new school year","am":"ትምህርት ቤቱ ከ642 በላይ ተማሪዎችን ተቀበለ","om":"Barumsi kun barattoota 642 ol fudhateera"}'::jsonb, '{"ar":"بدأت مدرسة دار القرآن الكريم لخديجة بنت خويلد عامها الدراسي الجديد باستقبال أكثر من 642 طالباً وطالبة في مختلف الصفوف من التمهيد إلى الصف الخامس. تم تجهيز الفصول الدراسية وتوفير جميع المستلزمات التعليمية. كما تم استقبال معلمين جدد مؤهلين للانضمام إلى هيئة التدريس، ليصل عدد المعلمين إلى أكثر من 10 معلمين.","en":"Dar Al-Quran School for Khadija bint Khuwaylid began its new school year welcoming over 642 students across all grades from preparatory to Grade 5. Classrooms were prepared and all educational supplies provided. New qualified teachers were also welcomed, bringing the total to more than 10 teachers.","am":"ዳር አል-ቁርአን ትምህርት ቤት አዲሱን የትምህርት ዓመት ከ642 በላይ ተማሪዎችን ተቀበሎ ጀምሯል።","om":"Barumsi Daar Al-Quraan waggaa haaraa barattoota 642 ol fudhateera. Kutaa hunda qopheessiteera."}'::jsonb),
('ann-4', '{"ar":"مشروع إفطار رمضان لـ 82 طفلاً","en":"Ramadan Iftar Project for 82 Children","am":"ለ82 ልጆች የረመዳን እርዳታ ፕሮጀክት","om":"Piroogiraamii iftaar Ramadaanaa ilmuu 82"}'::jsonb, 'charity', '2025-03-01', 'https://images.pexels.com/photos/8145478/pexels-photo-8145478.jpeg?auto=compress&cs=tinysrgb&w=800', '{"ar":"يواصل بيت الرحمة تقديم وجبة الإفطار اليومية لـ 82 طفلاً من الأطفال المساكين","en":"Bayt Al-Rahma continues providing daily Iftar meals for 82 poor children","am":"ቤት አል-ራህማ ለ82 ልጆች በየቀኑ የእርዳታ ምሳ መስጠቱን ይቀጥላል","om":"Bayt Al-Rahmaan nyaata iftaaraa guyyaa guyyaa ilmuu 82 kenna jira"}'::jsonb, '{"ar":"يواصل بيت الرحمة الخيرية مشروعه الرمضاني المبارك بتقديم وجبة الإفطار اليومية لـ 82 طفلاً من الأطفال المساكين في المنطقة. يهدف المشروع إلى تخفيف معاناة الأسر الفقيرة وتوفير وجبة مغذية للأطفال خلال الشهر الفضيل. يدعو البيت جميع المحسنين للإسهام في هذا المشروع الخيري عبر قناة التيليجرام.","en":"Bayt Al-Rahma Charity continues its blessed Ramadan project providing daily Iftar meals for 82 poor children in the region. The project aims to alleviate the suffering of poor families and provide nutritious meals for children during the holy month. The charity invites all benefactors to contribute via its Telegram channel.","am":"ቤት አል-ራህማ የረመዳን ፕሮጀክቱን በመቀጠል ለ82 ልጆች በየቀኑ ምሳ ይሰጣል።","om":"Bayt Al-Rahmaan piroogiraamii Ramadaanaa itti fufiinsaan ilmuu 82 iftaara guyyaa kenna jira."}'::jsonb),
('ann-5', '{"ar":"بدء دراسة كتاب جديد في حلقة دار القرآن","en":"New Book Study Begins in the Study Circle","am":"አዲስ መጽሐፍ ጥናት ተጀምሯል","om":"Qorannoo kitaaba haaraa eegaleera"}'::jsonb, 'halqa', '2025-01-20', 'https://images.pexels.com/photos/8145478/pexels-photo-8145478.jpeg?auto=compress&cs=tinysrgb&w=800', '{"ar":"تبدأ حلقة دار القرآن دراسة كتاب عمدة الأحكام بعد صلاة العصر","en":"The Study Circle begins studying Umdat al-Ahkam after Asr prayer","am":"የዳር አል-ቁርአን ክበብ ከአስር ሰዓት በኋላ አዲስ መጽሐፍ ጥናት ይጀምራል","om":"Marii qorannoon kitaaba Umdat al-Ahkaam eegaluu ni danda''a"}'::jsonb, '{"ar":"تُعلن حلقة دار القرآن عن بدء دراسة كتاب عمدة الأحكام في الحلقة العلمية التي تعقد بعد صلاة العصر إلى المغرب. يُدرّس الكتاب الشيخ بأسلوب مبسط يسهل على الطلاب فهم الأحكام الفقهية من مصادرها الأصلية. يُرحب الحلقة بانضمام طلاب العلم الجدد الراغبين في دراسة الفقه.","en":"The Dar Al-Quran Study Circle announces the beginning of studying Umdat al-Ahkam in the study circle held from Asr to Maghrib. The book is taught in a simplified style that helps students understand Fiqh rulings from their original sources. New students of knowledge interested in studying Fiqh are welcome to join.","am":"የዳር አል-ቁርአን ክበብ አዲስ መጽሐፍ ጥናት ይጀምራል። አዳዲስ ተማሪዎች እንግዳ ይቀበላል።","om":"Marii qorannoon kitaaba Umdat al-Ahkaam qorachuu eegaleera. Barattoota haaraa dhihaatan ni fudhanna."}'::jsonb),
('ann-6', '{"ar":"ترميم منزل لعائلة محتاجة","en":"Home Renovation for a Needy Family","am":"ለተፈላጊ ቤተሰብ የቤት ጥገና","om":"Maatii hiyaanaa mana fooyya''uu"}'::jsonb, 'charity', '2025-02-15', 'https://images.pexels.com/photos/8145478/pexels-photo-8145478.jpeg?auto=compress&cs=tinysrgb&w=800', '{"ar":"أكمل بيت الرحمة ترميم منزل سابع لعائلة محتاجة في المنطقة","en":"Bayt Al-Rahma completed renovating its seventh home for a needy family in the region","am":"ቤት አል-ራህማ የሰባተኛውን ቤት ጥገና አጠናቀቀ","om":"Bayt Al-Rahmaan mana torbaffaa fooyya''eera"}'::jsonb, '{"ar":"بفضل الله ثم بدعم المحسنين، أكمل بيت الرحمة الخيرية ترميم منزل سابع لعائلة محتاجة في المنطقة. يهدف المشروع إلى تحسين الظروف المعيشية للأسر الفقيرة وتوفير بيئة صحية وآمنة. يُشرف البيت على جميع مراحل الترميم من تقييم الاحتياج إلى التسليم.","en":"By Allah''s grace and with the support of benefactors, Bayt Al-Rahma Charity completed renovating its seventh home for a needy family in the region. The project aims to improve living conditions for poor families and provide a healthy and safe environment. The charity oversees all renovation stages from needs assessment to delivery.","am":"በአላህ ምሕረት እና በተበራከቱ ድጋፍ፣ ቤት አል-ራህማ የሰባተኛውን ቤት ጥገና አጠናቀቀ።","om":"Tola Rabbii fi deggersa dhiiraan, Bayt Al-Rahmaan mana torbaffaa fooyya''eera."}'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- ============ posts ============
INSERT INTO posts (id, type, department_slug, title, media, content, date) VALUES
('post-1', 'image', 'center-hifz', '{"ar":"صور من حفل تخريج الحافظات","en":"Photos from the Hafizat Graduation","am":"የሂፍዝ ምሩቃን ምረቃ ምስሎች","om":"Suuraa shubbisa hafzuu milkaa''intotaa"}'::jsonb, 'https://images.pexels.com/photos/8145478/pexels-photo-8145478.jpeg?auto=compress&cs=tinysrgb&w=800', '{"ar":"لقطات مميزة من حفل تخريج الدفعة الأولى من حافظات القرآن الكريم بمركز دار القرآن. لحظات مؤثرة جمعت الفرح بالدموع، والشكر لله على نعمة حفظ كتابه.","en":"Special moments from the graduation ceremony of the first batch of Quran Hafizat at Dar Al-Quran Center. Touching moments combining joy with tears, and gratitude to Allah for the blessing of memorizing His Book.","am":"ከመጀመሪያው ወረቀት የቁርአን ምሩቃን ምረቃ ሥነ ሥርዓት ምስሎች።","om":"Suuraa shubbisa hafzuu milkaa''intotaa kan eegale."}'::jsonb, '2024-12-20'),
('post-2', 'video', 'school', '{"ar":"تلاوة طالبة من الصف الثالث","en":"Recitation by a Grade 3 Student","am":"ከ3ኛ ክፍል ተማሪ የቁርአን ንባብ","om":"Qara''i barattoota kutaa sadaffaa"}'::jsonb, 'https://images.pexels.com/photos/8145478/pexels-photo-8145478.jpeg?auto=compress&cs=tinysrgb&w=800', '{"ar":"تلاوة عطرة من القرآن الكريم بصوت إحدى طالبات الصف الثالث في مدرسة دار القرآن. تتجلى فيها ثمرة الجهد المبذول في تعليم التجويد للأطفال.","en":"A beautiful recitation of the Holy Quran by a Grade 3 student at Dar Al-Quran School, showcasing the fruits of effort invested in teaching Tajwid to children.","am":"ከ3ኛ ክፍል ተማሪ የቁርአን ንባብ።","om":"Qara''i barattoota kutaa sadaffaa Quraana qara''uu."}'::jsonb, '2025-02-10'),
('post-3', 'article', 'halqa', '{"ar":"أهمية دراسة كتب التراث الإسلامي","en":"The Importance of Studying Classical Islamic Texts","am":"የእስላም የቅርስ መጻሕፍትን ማጥናት አስፈላጊነት","om":"Barbaachisummaa qorannoo kitaabota Islaamaa dulloo"}'::jsonb, '', '{"ar":"تعد دراسة كتب التراث الإسلامي من أهم وسائل فهم الدين الإسلامي فهماً صحيحاً. فهذه الكتب التي ألفها علماء الأمة عبر القرون تمثل خلاصة فهمهم للنصوص الشرعية وتطبيقها في واقع الحياة. في حلقة دار القرآن، نحرص على دراسة هذه الكتب بمنهجية واضحة تجمع بين الفهم النظري والتطبيق العملي.","en":"Studying classical Islamic texts is one of the most important means of understanding the Islamic religion correctly. These books, authored by the nation''s scholars over centuries, represent the essence of their understanding of religious texts and their application in life. In the Dar Al-Quran Study Circle, we ensure studying these books with a clear methodology combining theoretical understanding with practical application.","am":"የእስላም የቅርስ መጻሕፍትን ማጥናት ከልዩ አስፈላጊነት ይኖራል።","om":"Qorannoon kitaabota Islaamaa dulloo barbaachisaa dha."}'::jsonb, '2025-01-25'),
('post-4', 'image', 'charity', '{"ar":"توزيع ملابس العيد على الأطفال","en":"Eid Clothing Distribution to Children","am":"ለልጆች የኢድ ልብስ ስበራ","om":"Uffata Iidaa ilmuuf qabachuu"}'::jsonb, 'https://images.pexels.com/photos/8145478/pexels-photo-8145478.jpeg?auto=compress&cs=tinysrgb&w=800', '{"ar":"وزع بيت الرحمة الخيرية ملابس العيد على أطفال الأسر المحتاجة، لإدخال الفرح والسرور على قلوبهم في يوم العيد. شارك في التوزيع عدد من المتطوعين.","en":"Bayt Al-Rahma Charity distributed Eid clothing to children of needy families, bringing joy and happiness to their hearts on Eid day. Several volunteers participated in the distribution.","am":"ቤት አል-ራህማ ለልጆች የኢድ ልብስ ሰበረ።","om":"Bayt Al-Rahmaan uffata Iidaa ilmuuf qabeera."}'::jsonb, '2025-02-28'),
('post-5', 'video', 'center-hifz', '{"ar":"كلمة من إحدى الخريجات","en":"A Word from One of the Graduates","am":"ከአንዱ ምሩቅ ቃል","om":"Jecha milkaa''intota tokko"}'::jsonb, 'https://images.pexels.com/photos/8145478/pexels-photo-8145478.jpeg?auto=compress&cs=tinysrgb&w=800', '{"ar":"كلمة مؤثرة من إحدى خريجات مركز حفظ القرآن الكريم، تتحدث فيها عن رحلتها في حفظ كتاب الله والتحديات والإنجازات.","en":"A touching speech from one of the Quran Memorization Center graduates, talking about her journey in memorizing the Book of Allah, the challenges, and the achievements.","am":"ከአንዱ ምሩቅ ቃል።","om":"Jecha milkaa''intota tokko."}'::jsonb, '2024-12-22'),
('post-6', 'article', 'school', '{"ar":"منهجية تعليم القاعدة النورانية للأطفال","en":"Methodology of Teaching Qaida Nuraniyyah to Children","am":"ለልጆች ቃዒደ ኑራኒያ የማስተማር ዘዴ","om":"Qaida Nuraaniyyaa ilmuuf barsiisuu mala"}'::jsonb, '', '{"ar":"تُعد القاعدة النورانية من أهم الوسائل لتعليم الأطفال قراءة القرآن الكريم بالتجويد. في مدرسة دار القرآن، نتبع منهجية متدرجة تبدأ بتعليم الحروف وأصواتها، ثم الكلمات، ثم الآيات. هذه المنهجية أثبتت فعاليتها في تخريج طلاب قادرين على قراءة القرآن بإتقان.","en":"Qaida Nuraniyyah is one of the most important tools for teaching children to read the Holy Quran with Tajwid. At Dar Al-Quran School, we follow a progressive methodology starting with letters and their sounds, then words, then verses. This methodology has proven effective in graduating students capable of reading the Quran with mastery.","am":"ቃዒደ ኑራኒያ ለልጆች ቁርአንን በተጅዊድ ለማስተማር ከልዩ አስፈላጊነት ይኖራል።","om":"Qaida Nuraaniyyaa ilmuuf Quraana Tajwiidaan barsiisuuf mala barbaachisaa dha."}'::jsonb, '2025-02-05')
ON CONFLICT (id) DO NOTHING;

-- ============ testimonials ============
INSERT INTO testimonials (id, name, role, quote, department_slug) VALUES
('test-1', 'أم عبد الله', '{"ar":"والدة طالبة في مركز الحفظ","en":"Parent of a Memorization Center student","am":"የማስታወሻ ማዕከል ተማሪ ወላጅ","om":"Haadha barartummaa Wiirtuu Hafzuu"}'::jsonb, '{"ar":"الحمد لله الذي بنعمته تتم الصالحات. ابنتي أتمت حفظ القرآن الكريم كاملاً في مركز دار القرآن، وأنا أسأل الله أن يجزي القائمين عليه خير الجزاء.","en":"Praise be to Allah, by Whose grace righteous deeds are completed. My daughter completed the full memorization of the Quran at Dar Al-Quran Center. I ask Allah to reward those in charge with the best reward.","am":"ምስጋና ለአላህ። ሴት ልጄ ቁርአንን በሙሉ አስታውሳለች።","om":"Galata Rabbii. Ilmiin koo Quraana guutuu hafuuteera."}'::jsonb, 'center-hifz'),
('test-2', 'أبو محمد', '{"ar":"ولي أمر طالب في المدرسة","en":"Parent of a School student","am":"የትምህርት ቤት ተማሪ ወላጅ","om":"Haadha barartummaa barumsa"}'::jsonb, '{"ar":"مدرسة دار القرآن مدرسة فاضلة، تعلم الأطفال القرآن والأخلاق. ابني تعلم فيها قراءة القرآن بالتجويد وأصبح متميزاً في أخلاقه.","en":"Dar Al-Quran School is an excellent school that teaches children the Quran and morals. My son learned to read the Quran with Tajwid and became outstanding in his character.","am":"ዳር አል-ቁርአን ትምህርት ቤት ግሩም ትምህርት ቤት ነው።","om":"Barumsi Daar Al-Quraan barumsa gaarii dha."}'::jsonb, 'school'),
('test-3', 'الشيخ أحمد', '{"ar":"إمام المسجد ومدرس في الحلقة","en":"Mosque Imam and Study Circle teacher","am":"የመስጊድ ኢማም እና በክበቡ መምህር","om":"Imaamii masjidaa fi barsiisa marii"}'::jsonb, '{"ar":"حلقة دار القرآن منارة علم في المنطقة، يستفيد منها الكثير من طلاب العلم. أسأل الله أن يبارك في هذه الحلقة وأن ينفع بها.","en":"Dar Al-Quran Study Circle is a beacon of knowledge in the region, benefiting many students of knowledge. I ask Allah to bless this circle and make it beneficial.","am":"የዳር አል-ቁርአን ክበብ በክልሉ የእውቀት መብራት ነው።","om":"Marii qorannoo Daar Al-Quraan naannoo kanaa ifa beekumsaati."}'::jsonb, 'halqa'),
('test-4', 'فاطمة', '{"ar":"مستفيدة من بيت الرحمة","en":"Beneficiary of Bayt Al-Rahma","am":"ከቤት አል-ራህማ ተጠቃሚ","om":"Fayyadamtuu Bayt Al-Rahmaa"}'::jsonb, '{"ar":"جزاكم الله خيراً على ما تقدمونه لنا من مساعدات. وجبات الإفطار التي تقدمونها لأطفالي ساهمت في تخفيف معاناتنا كثيراً.","en":"May Allah reward you with goodness for the assistance you provide us. The Iftar meals you offer my children have greatly alleviated our suffering.","am":"አላህ ይሁንልን። ለልጆቼ የሰጠችሁን ምሳ ችግሬን በጣም አቃለለ።","om":"Rabbiin galata isin galchee haa dha''u. Nyaata ilmuu kooaf kennitan naaf gargaareera."}'::jsonb, 'charity')
ON CONFLICT (id) DO NOTHING;

-- ============ timeline_events ============
INSERT INTO timeline_events (id, year, title, description) VALUES
('tl-1', '1438 هـ', '{"ar":"تأسيس مدرسة دار القرآن الكريم","en":"Founding of Dar Al-Quran School","am":"የዳር አል-ቁርአን ትምህርት ቤት መመስረት","om":"Barumsa Daar Al-Quraan kan hundeeffame"}'::jsonb, '{"ar":"تأسست المدرسة كأول أقسام المؤسسة، تبدأ بتعليم الأطفال قاعدة نورانية ثم قراءة القرآن ثم الصفوف من 1 إلى 5","en":"The school was founded as the first department, starting with teaching children Qaida Nuraniyyah then Quran reading then Grades 1-5","am":"ትምህርት ቤቱ እንደ መጀመሪያ ክፍል ተመሰረተ","om":"Barumsi kun akka kutaa tokkoffaa kan hundeeffame"}'::jsonb),
('tl-2', '1443 هـ', '{"ar":"تأسيس حلقة دار القرآن","en":"Founding of Dar Al-Quran Study Circle","am":"የዳር አል-ቁርአን ክበብ መመስረት","om":"Marii qorannoo Daar Al-Quraan kan hundeeffame"}'::jsonb, '{"ar":"تأسست الحلقة العلمية لدراسة كتب التراث الإسلامي بعد صلاة العصر","en":"The study circle was founded for studying classical Islamic texts after Asr prayer","am":"የጥናት ክበቡ ተመሰረተ","om":"Marii qorannoon kan hundeeffame"}'::jsonb),
('tl-3', '2014 م.أ', '{"ar":"تأسيس بيت الرحمة الخيرية","en":"Founding of Bayt Al-Rahma Charity","am":"ቤት አል-ራህማ በጎ አድራጎት መመስረት","om":"Bayt Al-Rahma Gargaarsa kan hundeeffame"}'::jsonb, '{"ar":"تأسس بيت الرحمة كذراع خيري للمؤسسة، يقدم وجبات يومية ومساعدات للمحتاجين","en":"Bayt Al-Rahma was founded as the charitable arm, providing daily meals and aid to the needy","am":"ቤት አል-ራህማ ተመሰረተ","om":"Bayt Al-Rahmaan kan hundeeffame"}'::jsonb),
('tl-4', '1446 هـ', '{"ar":"تأسيس مركز حفظ القرآن الكريم","en":"Founding of the Quran Memorization Center","am":"የቁርአን ማስታወሻ ማዕከል መመስረት","om":"Wiirtuu Hafzu Quraanaa kan hundeeffame"}'::jsonb, '{"ar":"تأسس المركز السكني لتخريج الحافظات لكتاب الله كاملاً، قبل 20 طالبة في الدفعة الأولى وتخرج 18 منهن","en":"The residential center was founded for graduating female Hafizat of the complete Quran, accepting 20 students in the first batch, 18 of whom graduated","am":"ማዕከሉ ተመሰረተ","om":"Wiirtuun kan hundeeffame"}'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- ============ site_settings ============
INSERT INTO site_settings (id, hero_title, hero_subtitle, contact_email, contact_location, org_telegram, developed_by, social)
VALUES (
  1,
  '{"ar":"دار القرآن الكريم لخديجة بنت خويلد","en":"Dar Al-Quran Al-Kareem for Khadija bint Khuwaylid","am":"ዳር አል-ቁርአን አል-ካሪም ለኻዲጃ ብንት ኽወይሊድ","om":"Daar Al-Quraan Al-Kariim Khadiija binti Khuwaylid"}'::jsonb,
  '{"ar":"نصرةً لكتاب الله وتعليماً لأبناء وبنات المسلمين","en":"In support of the Book of Allah and education for the children of Muslims","am":"የአላህን መጽሐፍ ለመደገፍ እና ለሙስሊሞች ልጆች ትምህርት","om":"Kitaaba Rabbii deeggannuu fi ilmaan Muslimootaa barsiisuu"}'::jsonb,
  'info@daralquran.org',
  '{"ar":"إثيوبيا","en":"Ethiopia","am":"ኢትዮጵያ","om":"Itoophiyaa"}'::jsonb,
  'https://t.me/daralquran',
  'Noor Studio',
  '{"telegram":"https://t.me/daralquran","whatsapp":"https://wa.me/251900000000","facebook":"https://facebook.com/daralquran","tiktok":"https://tiktok.com/@daralquran"}'::jsonb
)
ON CONFLICT (id) DO NOTHING;
